# mxabierto Alpine
# Minimal image based on Alpine Linux
# Build:
#   docker build -t mxabierto/alpine .
# Usage:
#   docker run --rm -it mxabierto/alpine

# This is a scratch image
FROM scratch

MAINTAINER bcessa <ben@pixative.com>

ADD rootfs.tar.gz /

CMD ["sh"]