# Use base wrapper as parent; it will add root ca certs and
# main binary on build by default
FROM mxabierto/go-bin-wrapper

# Add required assets, config files, etc

# Application-specific requirements
EXPOSE 3333
